In [2]:
pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in c:\users\acer\appdata\roaming\python\python313\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\acer\appdata\roaming\python\python313\site-packages (from plotly) (2.18.1)
Requirement already satisfied: packaging in c:\users\acer\appdata\roaming\python\python313\site-packages (from plotly) (25.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [4]:
df = pd.read_csv(r"C:\Users\acer\Downloads\IMDb Movies India.csv", encoding='latin1')
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

In [3]:
df.shape

(15509, 10)

In [4]:
df.describe()

            Rating
count  7919.000000
mean      5.841621
std       1.381777
min       1.100000
25%       4.900000
50%       6.000000
75%       6.800000
max      10.000000

In [5]:
df = df.dropna()

In [6]:
df.isna().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5659 entries, 1 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5659 non-null   object
 1   Year      5659 non-null   object
 2   Duration  5659 non-null   object
 3   Genre     5659 non-null   object
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   object
 6   Director  5659 non-null   object
 7   Actor 1   5659 non-null   object
 8   Actor 2   5659 non-null   object
 9   Actor 3   5659 non-null   object
dtypes: float64(1), object(9)
memory usage: 486.3+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dropna(inplace=True)

In [10]:
df.columns

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [11]:
df['Year']=df['Year'].str.replace(r'[()]', '', regex=True).astype(int)

In [12]:
df['Duration']=pd.to_numeric(df['Duration'].str.replace(' min', ''))

In [13]:
df['Genre']=df['Genre']
df=df.explode('Genre')
df['Genre'].fillna(df['Genre'].mode()[0], inplace=True)

C:\Users\acer\AppData\Local\Temp\ipykernel_20448\4252530505.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Genre'].fillna(df['Genre'].mode()[0], inplace=True)

In [14]:
df['Votes']=pd.to_numeric(df['Votes'].str.replace(',', ''))

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5659 entries, 1 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5659 non-null   object
 1   Year      5659 non-null   int64
 2   Duration  5659 non-null   int64
 3   Genre     5659 non-null   object
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   int64
 6   Director  5659 non-null   object
 7   Actor 1   5659 non-null   object
 8   Actor 2   5659 non-null   object
 9   Actor 3   5659 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 486.3+ KB

In [18]:
pip install nbformat

Defaulting to user installation because normal site-packages is not writeable
Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\acer\appdata\roaming\python\python313\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\acer\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat)
  Using cached rpds_py-0.30.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\acer\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-0.30.0-cp313-cp313-win_amd64.whl (240 kB)
Installing collected packages: fastjsonschema, rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, nbformat

   ---------------------------------------- 0/7 [fastjsonschema]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------- ---------------------------- 2/7 [attrs]
   ----------------- ---------------------- 3/7 [referencing]
   ----------------- ---------------------- 3/7 [referencing]
   ---------------------- ----------------- 4/7 [jsonschema-specifications]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------- ----------- 5/7 [jsonschema]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------- ----- 6/7 [nbformat]
   ---------------------------------------- 7/7 [nbformat]

Successfully installed attrs-26.1.0 fastjsonschema-2.21.2 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.37.0 rpds-py-0.30.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
year=px.histogram(df, x='Year', histnorm='probability density', nbins=30)
year.show()

In [10]:
avg_rating_by_year=df.groupby(['Year', 'Genre'])['Rating'].mean().reset_index()
top_genres=df['Genre'].value_counts().head(10).index
average_rating_by_year=avg_rating_by_year[avg_rating_by_year['Genre'].isin(top_genres)]
fig=px.line(avg_rating_by_year,x='Year', y='Rating', color='Genre')
fig.update_layout(title='Average Rating by Year for Top genres', xaxis_title='Year', yaxis_title='Average Rating')
fig.show()

In [11]:
rating_fig=px.histogram(df, x='Rating', histnorm='probability density', nbins=40)
rating_fig.update_layout(title='Distribution of Rating', title_x=0.5, title_pad=dict(t=20), title_font=dict(size=20), xaxis_title='Rating', yaxis_title='Probability Density')
rating_fig.show()

In [12]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score

In [16]:
df.drop('Name', axis=1, inplace=True)

In [18]:
genre_mean_rating=df.groupby('Genre')['Rating'].transform('mean')
df['Genre_mean_rating']=genre_mean_rating
director_mean_rating=df.groupby('Director')['Rating'].transform('mean')
df['Director_encoded']=director_mean_rating
actor1_mean_rating=df.groupby('Actor 1')['Rating'].transform('mean')
df['Actor1_encoded']=actor1_mean_rating
actor2_mean_rating=df.groupby('Actor 2')['Rating'].transform('mean')
df['Actor2_encoded']=actor2_mean_rating
actor3_mean_rating=df.groupby('Actor 3')['Rating'].transform('mean')
df['Actor3_encoded']=actor3_mean_rating

In [19]:
x=df[[ 'Year', 'Votes', 'Duration', 'Genre_mean_rating', 'Director_encoded', 'Actor1_encoded', 'Actor2_encoded', 'Actor3_encoded']]
y=df['Rating']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
Model=LinearRegression()
Model.fit(X_train,y_train)
Model_pred=Model.predict(X_test)

ValueError: could not convert string to float: '7,711'

In [27]:
print('The performance evaluation of Logistic Regression is below: ', '\n')
print('Mean squared error: ',mean_squared_error(y_test, Model_pred))
print('Mean absolute error: ',mean_absolute_error(y_test, Model_pred))
print('R2 score: ',r2_score(y_test, Model_pred))

The performance evaluation of Logistic Regression is below:

NameError: name 'Model_pred' is not defined

In [ ]:
x.head(5)

In [ ]:
y.head(5)

In [ ]:
data={'Year'; [2019], 'Votes': [36], 'Duration':[111], 'Genre_mean_rating':[5.8], 'Direction_encoded':[4.5],'Actor1_encode':[5.3], 'Actor2_encoded':[4.5], 'Actor3_encoded':[4.3]}
trail=pd.DataFrame(data)

In [ ]:
rating_predicted=Model.predict(trail)
print("Predicted Rating:", rating_predicted[0])